config/routes.rb
require 'domain_constraint'
require 'frontend_util'

Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v0 do
      get 'timeline', to: 'timeline#index'

      resources :news_items, only: [:index, :show] do
        collection do
          get 'categories'
        end
      end

      resources :play_events, only: [:create]
      resources :play_event_images, only: [:create]

      get 'stations/now-playing'
    end
  end

  constraints DomainConstraint.new(['ops.ojo.world', 'ops.ttrn.org', 'ops.ojo.world.dev', 'ops.ttrn.org.dev']) do
    get '/', to: redirect('/admin')
  end

  namespace :admin do

    get '/', to: 'home#index'

    resources :managed_twitter_accounts, only: [:create, :update]

    resources :news_items do
      member do
        get 'crop'
      end
    end
    resources :news_categories
    resources :users
    resources :stations
    resources :managed_instagram_accounts, only: :update

    get 'programs/calendar', to: 'programs#calendar' # b4 :programs or else overridden by 'show'
    resources :programs

    get '/metrics/this-time-then', to: 'metrics#ttt'
    get '/metrics/index', to: 'metrics#index'
    get '/metrics/peak-times', to: 'metrics#peak_times'

    get 'roles/manage'
    post 'roles/update'

    get 'users', to: 'administrators#list'

    get 'socialmedia', to: 'social_media_management#index'
    get 'socialmedia/instagram_oauth_connect', to: 'social_media_management#instagram_oauth_connect'
    get 'socialmedia/instagram_oauth_callback', to: 'social_media_management#instagram_oauth_callback'
  end

  devise_for :users, controllers: {
    confirmations: 'admin/user_confirmations',
    registrations: 'admin/user_registrations'
  }
  devise_scope :user do
    get '/confirmation-next-step' => 'admin/user_confirmations#next_step',
      as: 'confirmation_next_step'
    get '/confirmation-confirmed' => 'admin/user_confirmations#confirmed',
      as: 'confirmation_confirmed'
  end

  post '_jobs', to: 'job_runner#perform_now'
  get '_health', to: 'application#health'

end

app/views/admin/_nav.html.haml
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">TTRN Admin</a>
</div>
<div id="navbar" class="navbar-collapse collapse">
<ul class="nav navbar-nav navbar-right">
<li>
- if current_user
  = link_to 'Sign Out', destroy_user_session_path
- else
  = link_to 'Sign In', new_user_session_path
</li>
</ul>
</div>
</div>
</nav>

app/views/admin/_sidebar.html.haml
<ul class="nav nav-sidebar">
- if current_user # TODO(btc): is_admin
  %li
    = link_to 'Metrics', admin_metrics_index_path
  %li
    = link_to 'News', admin_news_items_path
  %li
    = link_to 'Stations', admin_stations_path
  %li
    = link_to 'Social Media', admin_socialmedia_path
  %li
    = link_to 'On-air Schedules', admin_programs_calendar_path
  %li
    = link_to 'Manage Admins', admin_users_path
  %li
    = link_to 'http://fms.ttrn.org:8088', target: '_blank' do
      <i class="fa fa-external-link" aria-hidden="true"></i>
      Streaming Server
  %li
    = link_to 'https://trello.com/b/i70eodyh/product-development', target: '_blank' do
      <i class="fa fa-external-link" aria-hidden="true"></i>
      Trello Board
  %li
    = link_to 'https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-1#/application/overview?applicationName=ttrn-api', target: '_blank' do
      <i class="fa fa-external-link" aria-hidden="true"></i>
      AWS Beanstalk
</ul>