config/routes.rb
require 'domain_constraint'
require 'frontend_util'

Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v0 do
      get 'timeline', to: 'timeline#index'

      resources :news_items, only: [:index, :show] do
        collection do
          get 'categories'
        end
      end

      resources :play_events, only: [:create]
      resources :play_event_images, only: [:create]

      get 'stations/now-playing'
    end
  end

  constraints DomainConstraint.new(['ops.ojo.world', 'ops.ttrn.org', 'ops.ojo.world.dev', 'ops.ttrn.org.dev']) do
    get '/', to: redirect('/admin')
  end

  namespace :admin do

    get '/', to: 'home#index'

    resources :managed_twitter_accounts, only: [:create, :update]

    resources :news_items do
      member do
        get 'crop'
      end
    end
    resources :news_categories
    resources :users
    resources :stations
    resources :managed_instagram_accounts, only: :update

    get 'programs/calendar', to: 'programs#calendar' # b4 :programs or else overridden by 'show'
    resources :programs

    get '/metrics/this-time-then', to: 'metrics#ttt'
    get '/metrics/index', to: 'metrics#index'
    get '/metrics/peak-times', to: 'metrics#peak_times'

    get 'roles/manage'
    post 'roles/update'

    get 'users', to: 'administrators#list'

    get 'socialmedia', to: 'social_media_management#index'
    get 'socialmedia/instagram_oauth_connect', to: 'social_media_management#instagram_oauth_connect'
    get 'socialmedia/instagram_oauth_callback', to: 'social_media_management#instagram_oauth_callback'
  end

  devise_for :users, controllers: {
    confirmations: 'admin/user_confirmations',
    registrations: 'admin/user_registrations'
  }
  devise_scope :user do
    get '/confirmation-next-step' => 'admin/user_confirmations#next_step',
      as: 'confirmation_next_step'
    get '/confirmation-confirmed' => 'admin/user_confirmations#confirmed',
      as: 'confirmation_confirmed'
  end

  post '_jobs', to: 'job_runner#perform_now'
  get '_health', to: 'application#health'

end

app/models/station.rb
class Station < ApplicationRecord
  has_many :programs
  has_many :play_events

  validates_presence_of :tag

  EventTypes = [:program, :song, :spot]

  def current_program
    active_program = self.programs.to_a.keep_if { |p|
      p.schedule.occurring_at? Time.now
    }.first
    active_program
  end

  def current_play_event
    candidate = play_events.last

    return nil if candidate == nil

    started = candidate.created_at.to_i
    duration = candidate.length_in_secs
    ending = started + duration
    now = Time.current.to_i

    now < ending ? candidate : nil
  end

  def now_playing
    NowPlaying.new self
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController

  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to admin_station_path(@station), notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: admin_station_path(@station) }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to admin_station_path(@station), notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to admin_stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name)
    end
end

app/controllers/api/v0/stations_controller.rb
class Api::V0::StationsController < Api::V0::BaseController
  include ::ActionController::Serialization

  def now_playing
    s = Station.find_by(tag: params[:tag])
    return render json: { error: "not found" }, status: :not_found if s == nil
    item = s.now_playing
    render json: item, serializer: Api::V0::NowPlayingSerializer
  end
end

app/views/admin/stations/_form.html.haml
= form_for [:admin, @station] do |f|
  - if @station.errors.any?
    #error_explanation
      %h2= "#{pluralize(@station.errors.count, "error")} prohibited this station from being saved:"
      %ul
        - @station.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/admin/stations/edit.html.haml
%h1 Editing station

= render 'form'

= link_to 'Show', admin_station_path(@station)
\|
= link_to 'Back', admin_stations_path

app/views/admin/stations/index.html.haml
%h1 Listing stations

= link_to 'New Station', new_admin_station_path

%table.table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @stations.each do |station|
      %tr
        %td= station.name
        %td= link_to 'Show', [:admin, station]
        %td= link_to 'Edit', edit_admin_station_path(station)
        %td= button_to 'Destroy', admin_station_path(station), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/admin/stations/new.html.haml
%h1 New station

= render 'form'

= link_to 'Back', admin_stations_path

app/views/admin/stations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @station.name

= link_to 'Edit', edit_admin_station_path(@station)
\|
= link_to 'Back', admin_stations_path