config/routes.rb
require 'domain_constraint'
require 'frontend_util'

Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v0 do
      get 'timeline', to: 'timeline#index'

      resources :news_items, only: [:index, :show] do
        collection do
          get 'categories'
        end
      end

      resources :play_events, only: [:create]
      resources :play_event_images, only: [:create]

      get 'stations/now-playing'
    end
  end

  constraints DomainConstraint.new(['ops.ojo.world', 'ops.ttrn.org', 'ops.ojo.world.dev', 'ops.ttrn.org.dev']) do
    get '/', to: redirect('/admin')
  end

  namespace :admin do

    get '/', to: 'home#index'

    resources :managed_twitter_accounts, only: [:create, :update]

    resources :news_items do
      member do
        get 'crop'
      end
    end
    resources :news_categories
    resources :users
    resources :stations
    resources :managed_instagram_accounts, only: :update

    get 'programs/calendar', to: 'programs#calendar' # b4 :programs or else overridden by 'show'
    resources :programs

    get '/metrics/this-time-then', to: 'metrics#ttt'
    get '/metrics/index', to: 'metrics#index'
    get '/metrics/peak-times', to: 'metrics#peak_times'

    get 'roles/manage'
    post 'roles/update'

    get 'users', to: 'administrators#list'

    get 'socialmedia', to: 'social_media_management#index'
    get 'socialmedia/instagram_oauth_connect', to: 'social_media_management#instagram_oauth_connect'
    get 'socialmedia/instagram_oauth_callback', to: 'social_media_management#instagram_oauth_callback'
  end

  devise_for :users, controllers: {
    confirmations: 'admin/user_confirmations',
    registrations: 'admin/user_registrations'
  }
  devise_scope :user do
    get '/confirmation-next-step' => 'admin/user_confirmations#next_step',
      as: 'confirmation_next_step'
    get '/confirmation-confirmed' => 'admin/user_confirmations#confirmed',
      as: 'confirmation_confirmed'
  end

  post '_jobs', to: 'job_runner#perform_now'
  get '_health', to: 'application#health'

end

app/models/news_item.rb
class NewsItem < ApplicationRecord

  validates_presence_of :title, :body
  validate :category_permitted

  def category_permitted
    return if category.nil? or category.empty?
    errors.add(:category, "cannot literally be #{category}") if NewsCategory::RESERVED_NAMES.include? category
    errors.add(:category, "must exist in News Categories. (#{category} does not).") unless NewsCategory.pluck(:name).include? category
  end

  # states
  # ======
  # TODO send push notification on publish
  VALID_STATES = %w[draft published unpublished republished].freeze
  validates :state, inclusion: { in: VALID_STATES,
                                 message: '%{value} is not a valid state' }
  before_validation Proc.new { |o| o.state = 'draft' if state == nil }

  scope :published, -> { where(state: :published).or(where(state: :republished)) }

  # attachments
  # ===========
  has_attached_file :photo, {
    preserve_files: true,
    styles: {
      thumb: { geometry: '100x100#' },
      large: { geometry: '800x800#' },
    }
  }
  crop_attached_file :photo, aspect: '1:1'
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_presence_of :photo

  after_save :compute_photo_dominant_color

  def compute_photo_dominant_color
    return unless changes[:photo_updated_at] != nil
    ComputeDominantColorJob.perform_later self, 'photo', 'photo_dominant_color'
  end
end

app/controllers/admin/news_items_controller.rb
class Admin::NewsItemsController < Admin::BaseController
  before_action :set_news_item, only: [:crop]
  load_and_authorize_resource

  # GET /news_items
  # GET /news_items.json
  def index
    scope = case params[:category]
            when nil
              NewsItem
            when 'Uncategorized'
              NewsItem.where(category: nil)
            else
              NewsItem.where(category: params[:category])
            end
    @news_items = scope.order(created_at: :desc).all
  end

  # GET /news_items/1
  # GET /news_items/1.json
  def show
  end

  # GET /news_items/new
  def new
    @news_item = NewsItem.new
  end

  # GET /news_items/1/edit
  def edit
  end

  # POST /news_items
  # POST /news_items.json
  def create
    @news_item = NewsItem.new(news_item_params)

    respond_to do |format|
      if @news_item.save
        format.html { redirect_to [:admin, @news_item], notice: 'News item was successfully created.' }
        format.json { render :show, status: :created, location: @news_item }
      else
        format.html { render :new }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_items/1
  # PATCH/PUT /news_items/1.json
  def update
    respond_to do |format|
      if @news_item.update(news_item_params)
        format.html { redirect_to [:admin, @news_item], notice: 'News item was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_item }
      else
        format.html { render :edit }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_items/1
  # DELETE /news_items/1.json
  def destroy
    @news_item.destroy
    respond_to do |format|
      format.html { redirect_to admin_news_items_url, notice: 'News item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def crop
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_item
      @news_item = NewsItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_item_params
      params.require(:news_item).permit(
        :title, :subtitle, :body, :photo, :straphead, :photo_caption, :state, :category,

        # these are required for gem 'papercrop' cropping
        :photo_original_w, :photo_original_h, :photo_box_w, :photo_aspect,
        :photo_crop_x, :photo_crop_y, :photo_crop_w, :photo_crop_h
      )
    end
end

app/controllers/api/v0/news_items_controller.rb
class Api::V0::NewsItemsController < Api::V0::BaseController
  include ::ActionController::Serialization

  def index
    q = NewsItem.published.order(created_at: :desc)

    if params[:before] or params[:after] then
      key = params[:by_date] ? 'created_at' : 'id'
      if params[:before] then
        value = params[:before]
        comparator = "#{key} < ?"
      end
      if params[:after] then
        value = params[:after]
        comparator = "#{key} > ?"
      end
      q = q.where(comparator, value)
    end

    if params[:limit] then
      q = q.limit(params[:limit])
    end

    render json: q.all, each_serializer: Api::V0::NewsItemSerializer
  end

  def show
    item = NewsItem.published.find(params[:id])
    render json: item, serializer: Api::V0::NewsItemSerializer
  end

  def categories
    serializer = if format_jsonapi then Api::V0::NewsCategorySerializer else nil end
    items = NewsCategory.select(:id, :name).order(name: :asc).all
    render json: items, each_serialilzer: serializer
  end

  private
  def format_jsonapi
    params[:format] == 'jsonapi'
  end
end

app/views/admin/news_items/_form.html.haml
= form_for [:admin, @news_item], html: { multipart: true } do |f|
  - if @news_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@news_item.errors.count, "error")} prohibited this news_item from being saved:"
      %ul
        - @news_item.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.submit save_btn_text, class: 'btn btn-primary'
  .form-group
    = f.label 'Photo (required)'
    = f.file_field :photo
    .help-block
      You'll have a chance to resize and crop the image after saving an initial draft.
  .form-group
    = f.label 'Category'
    = f.select :category, options_from_collection_for_select(NewsCategory.all.sort, 'name', 'name', @news_item.category)
  .form-group.form-group-sm
    = f.text_field :photo_caption, class: 'form-control', placeholder: 'Photo Caption (optional)'
  .form-group.form-group-sm
    = f.text_field :straphead, class: 'form-control', placeholder: 'Strap Head (optional)'
  .form-group.form-group-lg
    = f.text_field :title, class: 'form-control', placeholder: 'Title (required)'
  .form-group.form-group-sm
    = f.text_field :subtitle, class: 'form-control', placeholder: 'Subtitle/Drop Head (optional)'
  .form-group
    = f.bootsy_area :body, as: :bootsy, class: 'form-control', rows: 20, placeholder: 'Body (required)'
  .actions
    = f.submit save_btn_text, class: 'btn btn-primary'

app/views/admin/news_items/crop.html.haml
= form_for [:admin, @news_item] do |f|
  = f.cropbox :photo, width: 500
  = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/news_items/edit.html.haml
.container-fluid
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.mt20
      .panel.panel-default
        .panel-body
          = link_to 'Back', admin_news_items_path
          \|
          = link_to 'View', [:admin, @news_item]

          %h1 Edit...

          = render 'form', save_btn_text: 'Update'

app/views/admin/news_items/index.html.haml
.mt20.ml20
  = link_to new_admin_news_item_path do
    .btn.btn-primary
      New
.container-fluid
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.mt20
      .panel.panel-default
        .panel-body
          %ul.nav.nav-tabs
            %li{class: ("active" if params[:category] == nil)}
              = link_to "All", admin_news_items_path
            - NewsCategory.order(priority: :asc).all.each do |category|
              = activatable_li_tag_with_link category.name, admin_news_items_path(category: category.name)
            = activatable_li_tag_with_link "Uncategorized (#{ NewsItem.where(category: nil).count })", admin_news_items_path(category: 'Uncategorized')
          %table.table
            %thead
              %tr
                %th.col-md-1 thumb
                %th.col-md-6 title
                %th.col-md-2 state
                %th.col-md-3
                  -# actions
            %tbody
              - @news_items.each do |i|
                %tr
                  %td= image_tag i.photo.url(:thumb)
                  %td
                    = i.straphead
                    <br/>
                    = link_to i.title, [:admin, i]
                    <br/>
                    = i.subtitle
                  %td
                    %span.label= i.state
                  %td
                    .btn-group.btn-group-xs
                      -#    before         after           message       class
                      - [ ['draft',       'published',    'Publish',    'btn btn-primary'],
                          ['published',   'unpublished',  'Unpublish',  'btn btn-default'],
                          ['unpublished', 'republished',  'Republish',  'btn btn-primary'],
                          ['republished', 'unpublished',  'Unpublish',  'btn btn-default'],
                      ].each do |operation|
                        - if i.state == operation[0]
                          = button_to [:admin, i],
                            method: :patch,
                            params: { news_item: { state: operation[1] } },
                            class: operation[3] do
                            = operation[2]
                      = button_to [:admin, i], class: 'btn btn-danger', method: :delete do
                        %i.fa.fa-trash

app/views/admin/news_items/new.html.haml
.container-fluid
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.mt20
      .panel.panel-default
        .panel-body
          = link_to 'Back', admin_news_items_path
          <br>
          %h1 Create a New News Item
          = render 'form', save_btn_text: 'Save Draft'

app/views/admin/news_items/show.html.haml
.container-fluid
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.mt20
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            Preview
        .panel-body
          = link_to 'Edit', edit_admin_news_item_path(@news_item)
          \|
          = link_to 'Back', admin_news_items_path
          \|
          = link_to 'Crop Photo', crop_admin_news_item_path

          %p#notice= notice
          .news-item
            .category
              %h4
                (#{@news_item.category})
            .state
              %span.label= @news_item.state
            .photo
              = image_tag @news_item.photo.url(:large)
              <br>
              %small
                = @news_item.photo_caption
            .container-fluid
              .row
                .col-xs-0.col-sm-0.col-md-3.col-lg-3.mt20
                .col-xs-12.col-sm-12.col-md-6.col-lg-6.mt20
                  %h4
                    = @news_item.straphead
                  %h1
                    = @news_item.title
                  %h4
                    = @news_item.subtitle
                  %p
                    Published #{ @news_item.created_at.strftime "#{@news_item.created_at.day.ordinalize} %B, %Y" }
                  %p
                    = @news_item.body.html_safe
.container-fluid
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.mt20
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            Original Photo
        .panel-body
          .news-item
            .photo
              = image_tag @news_item.photo.url
.container-fluid
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.mt20
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            Thumbnail
        .panel-body
          .news-item
            .photo
              = image_tag @news_item.photo.url(:thumb)