config/routes.rb
require 'domain_constraint'
require 'frontend_util'

Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v0 do
      get 'timeline', to: 'timeline#index'

      resources :news_items, only: [:index, :show] do
        collection do
          get 'categories'
        end
      end

      resources :play_events, only: [:create]
      resources :play_event_images, only: [:create]

      get 'stations/now-playing'
    end
  end

  constraints DomainConstraint.new(['ops.ojo.world', 'ops.ttrn.org', 'ops.ojo.world.dev', 'ops.ttrn.org.dev']) do
    get '/', to: redirect('/admin')
  end

  namespace :admin do

    get '/', to: 'home#index'

    resources :managed_twitter_accounts, only: [:create, :update]

    resources :news_items do
      member do
        get 'crop'
      end
    end
    resources :news_categories
    resources :users
    resources :stations
    resources :managed_instagram_accounts, only: :update

    get 'programs/calendar', to: 'programs#calendar' # b4 :programs or else overridden by 'show'
    resources :programs

    get '/metrics/this-time-then', to: 'metrics#ttt'
    get '/metrics/index', to: 'metrics#index'
    get '/metrics/peak-times', to: 'metrics#peak_times'

    get 'roles/manage'
    post 'roles/update'

    get 'users', to: 'administrators#list'

    get 'socialmedia', to: 'social_media_management#index'
    get 'socialmedia/instagram_oauth_connect', to: 'social_media_management#instagram_oauth_connect'
    get 'socialmedia/instagram_oauth_callback', to: 'social_media_management#instagram_oauth_callback'
  end

  devise_for :users, controllers: {
    confirmations: 'admin/user_confirmations',
    registrations: 'admin/user_registrations'
  }
  devise_scope :user do
    get '/confirmation-next-step' => 'admin/user_confirmations#next_step',
      as: 'confirmation_next_step'
    get '/confirmation-confirmed' => 'admin/user_confirmations#confirmed',
      as: 'confirmation_confirmed'
  end

  post '_jobs', to: 'job_runner#perform_now'
  get '_health', to: 'application#health'

end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :roles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :lockable, :timeoutable, :confirmable

  validates_presence_of :full_name

  def has_role? role_name
    not self.roles.where(name: role_name).empty?
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/admin/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', [:admin, @user]
\|
= link_to 'Back', admin_users_path

app/views/admin/users/index.html.haml
%h1 Listing users

%table.table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= link_to 'Show', [:admin, user]
        %td= link_to 'Edit', edit_admin_user_path(user)
        %td= button_to 'Destroy', [:admin, user], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', admin_users_path

app/views/admin/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_user_path(@user)
\|
= link_to 'Back', admin_users_path